Assignment 2

In [ ]:
import pandas as pd
import numpy as np 

df_customers = pd.read_csv(r"E:\3rd Year\Machine Learning\Assignment\Dataset\AWCustomers.csv")
df_sales = pd.read_csv(r"E:\3rd Year\Machine Learning\Assignment\Dataset\AWSales.csv")


df_customers.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [24]:
df_sales.head()

   CustomerID  BikeBuyer  AvgMonthSpend
0       21173          1          50.97
1       13249          1          53.11
2       29350          1          54.08
3       13503          1          56.93
4       22803          1          55.41

Examining of Each feature of the Customer data

In [26]:
df_customers.shape

(18361, 24)

In [28]:
df_customers.isna().sum()

CustomerID                  0
Title                   18260
FirstName                   0
MiddleName               7789
LastName                    0
Suffix                  18358
AddressLine1                0
AddressLine2            18050
City                        0
StateProvinceName           0
CountryRegionName           0
PostalCode                  0
PhoneNumber                 0
BirthDate                   0
Education                   0
Occupation                  0
Gender                      0
MaritalStatus               0
HomeOwnerFlag               0
NumberCarsOwned             0
NumberChildrenAtHome        0
TotalChildren               0
YearlyIncome                0
LastUpdated                 0
dtype: int64

In [30]:
df_customers_new = df_customers.drop(['Title','MiddleName','Suffix','AddressLine2'],axis=1)

In [33]:
df_customers_new.head()

,CustomerID,FirstName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,Ryan,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,Julia,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,Theodore,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,Marshall,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [34]:
df_customers_new.isna().sum()

CustomerID              0
FirstName               0
LastName                0
AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
PhoneNumber             0
BirthDate               0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
LastUpdated             0
dtype: int64

Now do the same for the sales csv

In [36]:
df_sales.shape

(18355, 3)

In [38]:
df_sales.isna().sum()

CustomerID       0
BikeBuyer        0
AvgMonthSpend    0
dtype: int64

Merging the 2 dataframe

In [39]:
df = pd.merge(df_customers_new,df_sales,on="CustomerID")

In [42]:
avg_month_spend = df['AvgMonthSpend']

yearly_income = df['YearlyIncome']

In [43]:
df.shape

(18361, 22)

In [47]:
df.head()

,CustomerID,FirstName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,BirthDate,...,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
0,21173,Chad,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,1987-11-13,...,M,M,1,3,0,1,81916,2017-03-06,1,50.97
1,13249,Ryan,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,1972-07-21,...,M,M,1,2,1,2,81076,2017-03-06,1,53.11
2,29350,Julia,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,1985-11-09,...,F,S,0,3,0,0,86387,2017-03-06,1,54.08
3,13503,Theodore,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,1977-10-18,...,M,M,1,2,1,2,61481,2017-03-06,1,56.93
4,22803,Marshall,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,1975-02-05,...,M,S,1,1,0,0,51804,2017-03-06,1,55.41

Determining the datatype of each of the feature

In [49]:
df.dtypes

CustomerID                int64
FirstName                object
LastName                 object
AddressLine1             object
City                     object
StateProvinceName        object
CountryRegionName        object
PostalCode               object
PhoneNumber              object
BirthDate                object
Education                object
Occupation               object
Gender                   object
MaritalStatus            object
HomeOwnerFlag             int64
NumberCarsOwned           int64
NumberChildrenAtHome      int64
TotalChildren             int64
YearlyIncome              int64
LastUpdated              object
BikeBuyer                 int64
AvgMonthSpend           float64
dtype: object

In [51]:
ordinal = []
continous = []
categorical_string = []

for col, dtype in df.dtypes.items():
    if dtype==int:
        ordinal.append(col)
    elif dtype==float:
        continous.append(col)
    else:
        categorical_string.append(col)
        
print("Ordinal (rank based) features : \n{o}\n\n".format(o=ordinal))
print("Continous features : \n{c}\n\n".format(c=continous))
print("Categorical string features : \n{s}\n\n".format(s=categorical_string))

Ordinal (rank based) features :
['CustomerID', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome', 'BikeBuyer']


Continous features :
['AvgMonthSpend']


Categorical string features :
['FirstName', 'LastName', 'AddressLine1', 'City', 'StateProvinceName', 'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate', 'Education', 'Occupation', 'Gender', 'MaritalStatus', 'LastUpdated']

In [66]:
df.describe()

,CustomerID,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
count,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000
mean,20241.987092,0.610588,1.270301,0.338162,0.850389,72754.779642,0.551767,51.766744
std,5336.332731,0.487630,0.913989,0.568957,0.927315,30686.014313,0.497326,3.437684
min,11000.000000,0.000000,0.000000,0.000000,0.000000,25435.000000,0.000000,44.100000
25%,15621.000000,0.000000,1.000000,0.000000,0.000000,53312.000000,0.000000,49.410000
50%,20248.000000,1.000000,1.000000,0.000000,0.000000,61851.000000,1.000000,51.420000
75%,24863.000000,1.000000,2.000000,1.000000,2.000000,87410.000000,1.000000,53.590000
max,29483.000000,1.000000,5.000000,3.000000,3.000000,139115.000000,1.000000,65.290000

Categorising the feature according to their data type

In [68]:
df['Gender'].unique()

array(['M', 'F'], dtype=object)

In [70]:
df['Gender'] = df['Gender'].apply(lambda x : 1 if x=='M' else 0)

In [71]:
df['MaritalStatus'].unique()

array(['M', 'S'], dtype=object)

In [72]:
df['MaritalStatus'] = df['MaritalStatus'].apply(lambda x : 1 if x=='M' else 0)

In [73]:
df['LastUpdated'].unique()

array(['2017-03-06', '2017-03-07'], dtype=object)

In [74]:
df['LastUpdated'] = df['LastUpdated'].apply(lambda x : 1 if x=='2017-03-06' else 2)

In [75]:
categorical_string.remove('MaritalStatus')
categorical_string.remove('LastUpdated')
categorical_string.remove('Gender')

In [77]:
df_encoded = pd.get_dummies(df,columns=categorical_string)

In [79]:
df_encoded.head()

,CustomerID,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,...,Education_Bachelors,Education_Graduate Degree,Education_High School,Education_Partial College,Education_Partial High School,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
0,21173,0,1,1,3,0,1,81916,1,1,...,True,False,False,False,False,True,False,False,False,False
1,13249,0,1,1,2,1,2,81076,1,1,...,False,False,False,True,False,True,False,False,False,False
2,29350,0,0,0,3,0,0,86387,1,1,...,True,False,False,False,False,True,False,False,False,False
3,13503,0,1,1,2,1,2,61481,1,1,...,False,False,False,True,False,False,False,False,False,True
4,22803,0,0,1,1,0,0,51804,1,1,...,False,False,False,True,False,False,False,False,False,True

In [80]:
df_encoded.dtypes.unique()

array([dtype('int64'), dtype('float64'), dtype('bool')], dtype=object)

Applying binning methods to continuous and categorical datatype to reduce the noise

In [83]:
df_encoded['YearlyIncome'] = pd.cut(df_encoded['YearlyIncome'],bins=5).apply(lambda x : (x.left+x.right)/2.0)
df_encoded['AvgMonthSpend'] = pd.cut(df_encoded['AvgMonthSpend'],bins=5).apply(lambda x : (x.left+x.right)/2.0)

In [85]:
df['AvgMonthSpend']

0        50.97
1        53.11
2        54.08
3        56.93
4        55.41
         ...
18356    48.14
18357    50.23
18358    49.56
18359    51.42
18360    52.27
Name: AvgMonthSpend, Length: 18361, dtype: float64

In [86]:
df_encoded.head()

,CustomerID,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,...,Education_Bachelors,Education_Graduate Degree,Education_High School,Education_Partial College,Education_Partial High School,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
0,21173,0,1,1,3,0,1,82223.8295,1,1,...,True,False,False,False,False,True,False,False,False,False
1,13249,0,1,1,2,1,2,82223.8295,1,1,...,False,False,False,True,False,True,False,False,False,False
2,29350,0,0,0,3,0,0,82223.8295,1,1,...,True,False,False,False,False,True,False,False,False,False
3,13503,0,1,1,2,1,2,67654.5950,1,1,...,False,False,False,True,False,False,False,False,False,True
4,22803,0,0,1,1,0,0,67654.5950,1,1,...,False,False,False,True,False,False,False,False,False,True

    Normalization Of Data

In [88]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [90]:
income_final = scaler.fit_transform(df_encoded['YearlyIncome'].values.reshape(-1,1))
monthly_spend_final = scaler.fit_transform(df_encoded['AvgMonthSpend'].values.reshape(-1,1))

In [91]:
data = scaler.fit_transform(df_encoded)

In [93]:
data = pd.DataFrame(data)

Calculating similarity between yearly income and average monthly spend

In [96]:
income_final = pd.Series(income_final.flatten())
monthly_spend_final = pd.Series(monthly_spend_final.flatten())

In [98]:
SMS = np.sum(income_final==monthly_spend_final)/(len(income_final))

In [99]:
SMS

np.float64(0.10451500462937749)

In [101]:

JS = len(set((income_final)).intersection(monthly_spend_final))/(len(set(income_final).union(monthly_spend_final)))

In [103]:
JS

0.25

In [105]:
#cosine similarity

def cosine_similarity(a,b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

CS = cosine_similarity(income_final,monthly_spend_final)

In [106]:
CS

np.float64(0.8257839690306875)